// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXRHJtr53tTmXieImiyJSU6SG4RZKNLEA',
    appId: '1:292057146230:web:8912c6cdd4fa89f269d057',
    messagingSenderId: '292057146230',
    projectId: 'pawtopia-b8e1d',
    authDomain: 'pawtopia-b8e1d.firebaseapp.com',
    storageBucket: 'pawtopia-b8e1d.firebasestorage.app',
    measurementId: 'G-74XGE13CNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPVUyeh34-U6WbHsnhcBw5bGKM4PYrFnU',
    appId: '1:292057146230:android:b34b7f1344af130969d057',
    messagingSenderId: '292057146230',
    projectId: 'pawtopia-b8e1d',
    storageBucket: 'pawtopia-b8e1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNy_QfOk5SfuZvQcvYtL62GKSRZZXKDbM',
    appId: '1:292057146230:ios:baabe7013863478469d057',
    messagingSenderId: '292057146230',
    projectId: 'pawtopia-b8e1d',
    storageBucket: 'pawtopia-b8e1d.firebasestorage.app',
    iosBundleId: 'com.example.paw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNy_QfOk5SfuZvQcvYtL62GKSRZZXKDbM',
    appId: '1:292057146230:ios:baabe7013863478469d057',
    messagingSenderId: '292057146230',
    projectId: 'pawtopia-b8e1d',
    storageBucket: 'pawtopia-b8e1d.firebasestorage.app',
    iosBundleId: 'com.example.paw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXRHJtr53tTmXieImiyJSU6SG4RZKNLEA',
    appId: '1:292057146230:web:d520d9d76a359be069d057',
    messagingSenderId: '292057146230',
    projectId: 'pawtopia-b8e1d',
    authDomain: 'pawtopia-b8e1d.firebaseapp.com',
    storageBucket: 'pawtopia-b8e1d.firebasestorage.app',
    measurementId: 'G-T7QL1RPRX8',
  );
}
